<div class="px-content">

  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>competencia">Evaluacion</a></li>
    <li class="active">Pruebas</li>
  </ol>

  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Evaluacion</h1>
  </div>

  <div class="panel">
    <div class="panel-heading">
      <div class="panel-title">Filtros</div>
    </div>
    <form class="panel-body">
      <fieldset class="form-group col-sm-6">
        <label for="form-group-input-1">Evaluacion</label>
        <select class="form-control" id="evaluacion" name="evaluacion" >
          <option selected="selected" disabled="disabled">--SELECCIONE--</option>
          <?php while($reg=$this->evaluacion->fetch_object()): ?>
            <option value="<?php echo $reg->IDEVALUACION; ?>"><?php echo $reg->NOMBRE; ?></option>
          <?php endwhile; ?>
        </select>
      </fieldset>      

    </form>
    <div class="panel-footer text-right">
      <button type="button" id="btn_consultar" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Consultar</button>
    </div>
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Relacion de Evaluaciones Pendientes</div>
        </div>
        <div class="panel-body">
          <table class="table table-hover" id="tablaevaluacion" width="100%">
            <thead>
              <tr>                  
                <th>NOMBRE</th>
                <th>CARGO</th>
                <th>FECHA ASIGNACION</th>
                <th>ASIGNADO POR</th>
                <th>OPCIONES</th>                  
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>


<div class="modal fade" id="m_dar_prueba" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="title_prueba">Evaluacion de Competencias</h4>
      </div>
      <div class="modal-body">

        <form class="" id="form_prueba">  

          <input style="display: none;" type="text" name="codigos" id="codigos">

          <div class="panel">

            <div class="panel-body">
              <div class="wizard wizard-bordered" id="wizard-basic">
                <div class="wizard-wrapper">
                  <ul class="wizard-steps" id="div_cabecera">

                    <li data-target="#wizard-example-step1">
                      <span class="wizard-step-number">1</span>
                      <span class="wizard-step-complete"><i class="fa fa-check text-success"></i></span>
                      <span class="wizard-step-caption">Nombre Competencia
                        <span class="wizard-step-description">Marque solo una opcion</span>
                      </span>
                    </li>                                    

                  </ul>
                </div>

                <div id="div_body" class="wizard-content">

                  <div class="wizard-pane" id="wizard-example-step1">
                    <h4 class="m-y-2">Nombre de la competencia</h4>
                    <p>
                     <label class="custom-control custom-radio">
                      <input type="radio" id="custom-radio-3" name="b" class="custom-control-input">
                      <span class="custom-control-indicator"></span>
                      1
                    </label>
                    <label class="custom-control custom-radio">
                      <input type="radio" id="custom-radio-4" name="a" class="custom-control-input">
                      <span class="custom-control-indicator"></span>
                      2
                    </label>
                  </p>
                  <div class="pull-right">
                    <button type="button" class="btn btn-primary" data-wizard-action="next">Siguiente</button>
                  </div>
                </div>              
              
              </div>
            </div>
          </div>
        </div>

      </form>

    </div>    
  </div>
</div>
</div>