<div class="px-content">

  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>competencia">Competencia</a></li>
    <li class="active">Registro de Competencias</li>
  </ol>

  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Competencias</h1>
  </div> 
  
  <div class="panel-body">
    <button type="button" id="btn_nuevo_competencia" class="btn btn-md btn-primary btn-outline btn-3d btn-block" data-toggle="modal" data-target="#m_addcompetencia">Nueva Competencia</button>      
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Relacion de Competencias</div>
        </div>
        <div class="panel-body">
          <table class="table table-hover" id="tablacompetencias" width="100%">
            <thead>
              <tr>
                <th>ID</th>
                <th>NOMBRE</th>
                <th>ESTADO</th>
                <th>FECHA CREACION</th>
                <th>OPCIONES</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="modal fade" id="m_addcompetencia" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="title_competencia"></h4>
      </div>
      <div class="modal-body">

        <form class="" id="form_competencia">          

          <div class="form-group" style="display: none;">
              <label class="control-label required" for="required-input">IDCOMPETENCIA</label>
              <input type="text" class="form-control" id="idcompetencia" name="idcompetencia" autocomplete="off" maxlength="30">
          </div>

          <div class="form-group">
              <label class="control-label required" for="required-input">Nombre de la Competencia</label>
              <input type="text" class="letras form-control" id="nombre" name="nombre" autocomplete="off" maxlength="30">
          </div>

          <div class="row">

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Conducta 1</label>
              <input type="text" class="form-control" id="conducta1" name="conducta[]" autocomplete="off" maxlength="500">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Conducta 2</label>
              <input type="text" class="form-control" id="conducta2" name="conducta[]" autocomplete="off" maxlength="500">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Conducta 3</label>
              <input type="text" class="form-control" id="conducta3" name="conducta[]" autocomplete="off" maxlength="500">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Conducta 4</label>
              <input type="text" class="form-control" id="conducta4" name="conducta[]" autocomplete="off" maxlength="500">
            </div>

          </div>

          <div class="form-group">
              <label class="control-label" for="required-input">Observacion</label>
              <textarea class="form-control" id="observacion" name="observacion"></textarea>
          </div>          

        </form>

        <div class="form-group has-error">              
          <small class="form-message" id="msj_competencia"></small>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>        
        <button type="button" class="btn btn-primary m-r-1" id="btn_add_competencia">Guardar</button>
        <button type="button" class="btn btn-primary m-r-1" id="btn_update_competencia">Actualizar</button>           
      </div>
    </div>
  </div>
</div>