<div class="px-content">

  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>evaluacion">Evaluacion</a></li>
    <li class="active">Apertura de Evaluacion</li>
  </ol>

  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Apertura de Evaluacion</h1>
  </div> 
  
  <div class="panel-body">
    <button type="button" id="btn_nuevo_evaluacion" class="btn btn-md btn-primary btn-outline btn-3d btn-block" data-toggle="modal" data-target="#m_addevaluacion">Nueva Evaluacion</button>      
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Relacion de Competencias</div>
        </div>
        <div class="panel-body">
          <table class="table table-hover" id="tablaevaluciones" width="100%">
            <thead>
              <tr>
                <th>ID</th>
                <th>NOMBRE</th>
                <th>FECHA APERTURA</th>
                <th>FECHA CIERRE</th>
                <th>CANT. COMPETENCIAS</th>
                <th>ESTADO</th>
                <th>FECHA CREACION</th>
                <th>OPCIONES</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="modal_select2 modal fade" id="m_addevaluacion" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="title_evaluacion"></h4>
      </div>
      <div class="modal-body">

        <form class="" id="form_evaluacion">          

          <div class="form-group" style="display: none;">
            <label class="control-label required" for="required-input">IDEVALUACION</label>
            <input type="text" class="form-control" id="idevaluacion" name="idevaluacion" autocomplete="off" maxlength="30">
          </div>

          <div class="form-group">
            <label class="control-label required" for="required-input">Nombre de la Evaluacion</label>
            <input type="text" class="form-control" id="nombre" name="nombre" autocomplete="off" maxlength="30">
          </div>

          <div class="form-group">
            <label class="control-label required" for="required-input">Rango de Fechas</label>
            <div class="input-daterange input-group" >
              <input type="date" class="form-control" name="fecha_apertura" id="fecha_apertura" placeholder="Fecha Apertura">
              <small class="text-muted">Fecha Apertura</small>
              <span class="input-group-addon">a</span>
              <input type="date" class="form-control" name="fecha_cierre" id="fecha_cierre" placeholder="Fecha Cierre">
              <small class="text-muted">Fecha Cierre</small>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label required" for="required-input">Competencias</label>
            <select class="select2 form-control select2-primary" id="competencia" multiple name="competencia[]" placeholder="Seleccione Competencias">
              
            </select>            
          </div>

          <!-- 
          <div class="row">

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Fecha Apertura</label>
              <input type="text" class="datepicker form-control" id="fecha_apertura" name="fecha_apertura" autocomplete="off">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Fecha Cierre</label>
              <input type="date" class="form-control" id="fecha_cierre" name="fecha_cierre" autocomplete="off">
            </div>            

          </div>
          -->

        <div class="form-group">
          <label class="control-label" for="required-input">Observacion</label>
          <textarea class="form-control" id="observacion" name="observacion"></textarea>
        </div>          

      </form>

      <div class="form-group has-error">              
        <small class="form-message" id="msj_evaluacion"></small>
      </div>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn" data-dismiss="modal">Cerrar</button>        
      <button type="button" class="btn btn-primary m-r-1" id="btn_add_evaluacion">Guardar</button>
      <button type="button" class="btn btn-primary m-r-1" id="btn_update_evaluacion">Actualizar</button>           
    </div>
  </div>
</div>
</div>