<!-- Custom styling -->
  <style>
    .page-about-us-header.page-header {
      padding-top: 90px;
      padding-bottom: 90px;
    }

    .page-about-us-text {
      position: relative;
      padding-top: 60px;
      padding-bottom: 60px;
    }

    .page-about-us-team-avatar {
      width: 80px;
    }

    .page-about-us-team-avatar img {
      width: 100%;
    }
  </style>
  <!-- / Custom styling -->

<div class="px-content">

    <div class="page-about-us-header page-header m-b-0 b-b-0 text-xs-center bg-default">
      <h1 class="m-b-1 font-size-28 font-weight-bold">YICHANG</h1><br>
      <span class="font-size-18 font-weight-semibold">ALIADOS ESTRATÉGICOS EN LA GESTIÓN DE DISTRIBUCIÓN</span>
    </div>

    <!-- Contacts -->

    <div class="page-wide-block">
      <div class="box m-a-0 valign-middle border-radius-0 text-xs-center font-size-14">
        <a href="#" class="box-cell col-md-4 p-x-1 p-y-2 text-white" style="background: #4ab6d5;"><i class="fa fa-twitter"></i>&nbsp;&nbsp;@yichang</a>
        <a href="#" class="box-cell col-md-4 p-x-1 p-y-2 text-white" style="background: #1a7ab9;"><i class="fa fa-facebook-square"></i>&nbsp;&nbsp;yichang</a>
        <a href="#" class="box-cell col-md-4 p-x-1 p-y-2 text-white" style="background: #888;"><i class="fa fa-envelope"></i>&nbsp;&nbsp;support@yichang.com</a>
      </div>
    </div>

    <!-- / Contacts -->

    <!-- About text -->

    <div class="page-about-us-text page-block panel m-y-0 b-a-0 border-radius-0 font-size-16">
      <div class="m-x-auto" style="max-width: 800px;">
        <p>
          Somos una empresa importadora, comercializadora y distribuidora en el Perú con más de 80 años de experiencia como operador logístico.
Nuestra Misión: Generamos vínculos de confianza que superan la relación comercial en la gestión de distribución.
        </p>
        <p>
          Brindamos servicios logísticos integrales, para ello nos respaldamos en nuestra experiencia, cobertura del mercado, un excelente equipo técnico y en nuestros 5 pilares organizacionales:
        </p>
        <p>
          Contamos con marcas propias en diferentes categorías reconocidas en el mercado. En la actualidad, manejamos y representamos de manera exclusiva más de 35 marcas líderes a nivel mundial.
        </p>
      </div>
    </div>

    <!-- / About text -->



  </div>

  <script type="text/javascript">
    
    $(function() {
      $('.page-about-us-header').pxResponsiveBg({
        backgroundImage: 'public/demo/bgs/7.jpg',
        overlay: '#000'
      });
    });
  </script>